[package]
name = "mjolnir-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
mjolnir-core = { workspace = true }
mjolnir-image = { workspace = true }
mjolnir-storage = { workspace = true }
mjolnir-backup = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(windows)'.dependencies]
mjolnir-vss = { workspace = true }
