[package]
name = "mjolnir-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
mjolnir-core = { workspace = true }
serde = { workspace = true }
blake3 = { workspace = true }
argon2 = { workspace = true }
aes-gcm = { workspace = true }
zeroize = { workspace = true }
