[package]
name = "mjolnir-vss"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
mjolnir-core = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Ole",
    "Win32_System_Variant",
    "Win32_Storage_Vss",
    "Win32_Security",
] }
windows-core = { workspace = true }

[dev-dependencies]
mjolnir-storage = { workspace = true }
windows = { workspace = true, features = ["Win32_Foundation"] }
